Repository threatgrid/ctia, pull requests merged in 2018-04, with the labels that each got.

#692 Set the correct KMS Key to be used on S3 uploads
  build/debian-package.sh
Labels: in progress

#694 Issue 693 scope parameter
  project.clj
  resources/ctia-default.properties
  src/ctia/auth/jwt.clj
  src/ctia/properties.clj
  test/ctia/auth/jwt_test.clj
  test/ctia/http/routes/judgement_test.clj
Labels: review

#690 Fix the function that count the max number of entities in a bundle
  project.clj
  src/ctia/http/routes/bundle.clj
  test/ctia/http/routes/bundle_test.clj
  test/ctia/test_helpers/core.clj
  test/data/queries.graphql
Labels: bug, review
