Repository threatgrid/ctia, pull requests merged in 2018-11, with the labels that each got.

#749 Bump to clj-momo 0.2.29
  project.clj
Labels: review

#751 Added Event read-record store fn, disabled event get by external-id
  src/ctia/entity/event.clj
  src/ctia/entity/event/store.clj
  src/ctia/http/routes/crud.clj
  src/ctia/store.clj
  test/ctia/entity/event_test.clj
Labels: review

#754 handle casebook not found on operation routes
  src/ctia/entity/casebook.clj
  test/ctia/entity/casebook_test.clj
Labels: review

#755 Recursively ignore schema_version
  src/ctia/entity/indicator.clj
  src/ctia/schemas/core.clj
  src/ctia/schemas/utils.clj
  test/ctia/bundle/routes_test.clj
  test/ctia/schemas/utils_test.clj
Labels: review

#757 Use the latest version of CTIM (1.0.6)
  project.clj
Labels: review

#758 Allow Regular users bundle import capability
  src/ctia/auth/capabilities.clj
  src/ctia/bundle/routes.clj
  src/ctia/schemas/core.clj
Labels: review

#760 Bundle import: Return errors instead of a 500 for invalid relationships
  src/ctia/flows/crud.clj
  test/ctia/flows/crud_test.clj
Labels: bug, review

#762 Added an explicit message for verdict 404
  src/ctia/observable/routes.clj
  test/ctia/http/routes/observable/verdict_test.clj
Labels: review

#761 Use ctim 1.0.7
  project.clj
  src/ctia/entity/vulnerability/mapping.clj
  test/data/vulnerability_fragments.graphql
Labels: in progress
