Repository threatgrid/ctia, pull requests merged in 2019-01, with the labels that each got.

#772 bundle/export enabled to specify relationship filters
  src/ctia/bundle/core.clj
  src/ctia/bundle/routes.clj
  test/ctia/bundle/routes_test.clj
Labels: review

#773 Add Client-Dev Container
  containers/client-dev/README.md
  containers/client-dev/ctia/config/ctia.properties
  containers/client-dev/docker-compose.yml
  containers/client-dev/elasticsearch/config/.placeholder
Labels: No QA, review

#774 Remove config for missing Riemann from demo
  containers/demo/ctia/config/ctia.properties
Labels: review

#775 Improved client-dev README
  containers/client-dev/README.md
Labels: in progress

#776 Update client-dev container names
  containers/client-dev/ctia/config/ctia.properties
Labels: in progress

#779 Fix client-dev and demo container setup, remove nrepl support
  README.md
  containers/client-dev/ctia/config/ctia.properties
  containers/demo/ctia/config/ctia.properties
  doc/properties.org
  project.clj
  resources/ctia-default.properties
  src/ctia/init.clj
  src/ctia/properties.clj
  test/ctia/test_helpers/core.clj
Labels: in progress

#780 Docker HUB docker-compose config (demo and client-dev)
  containers/client-dev/README.md
  containers/client-dev/docker-compose.yml
  containers/demo/docker-compose.yml
Labels: review
