Repository threatgrid/ctia, pull requests merged in 2019-07, with the labels that each got.

#829 Fix a NPE while attempting to convert an ID on Bulk Export
  src/ctia/bulk/core.clj
  test/ctia/bulk/core_test.clj
  test/ctia/flows/hooks/kafka_event_hook_test.clj
Labels: review

#830 Use a rebalance listener instead of a sleep to wait for Kafka rebalance
  src/ctia/lib/kafka.clj
  test/ctia/flows/hooks/kafka_event_hook_test.clj
Labels: review

#831 Add rate limiting to CTIA
  README.md
  doc/properties.org
  project.clj
  resources/ctia-default.properties
  src/ctia/auth.clj
  src/ctia/auth/allow_all.clj
  src/ctia/auth/jwt.clj
  src/ctia/auth/static.clj
  src/ctia/auth/threatgrid.clj
  src/ctia/http/handler.clj
  src/ctia/http/middleware/ratelimit.clj
  src/ctia/http/server.clj
  src/ctia/lib/redis.clj
  src/ctia/properties.clj
  test/ctia/auth/jwt_test.clj
  test/ctia/entity/judgement_test.clj
  test/ctia/http/middleware/ratelimit_test.clj
Labels: review

#832 Fix the redis properties schema used by the rate limit
  src/ctia/properties.clj
Labels: bug, review

#833 Multiple JWT keys support
  doc/properties.org
  project.clj
  resources/cert/ctia-jwt-2.csr
  resources/cert/ctia-jwt-2.key
  resources/cert/ctia-jwt-2.pub
  resources/cert/gen_cert.sh
  src/ctia/auth/jwt.clj
  src/ctia/http/server.clj
  src/ctia/properties.clj
  test/ctia/auth/jwt_test.clj
  test/ctia/entity/judgement_test.clj
Labels: enhancement

#834 Update jquery and handlebar deps in Swagger UI
  resources/swagger-ui/index.html
  resources/swagger-ui/lib/handlebars-v4.1.2.js
  resources/swagger-ui/lib/jquery-3.4.1.min.js
  resources/swagger-ui/lib/jquery-migrate-1.4.1.min.js
  resources/swagger-ui/lib/jquery-migrate-3.0.1.min.js
Labels: review

#826 Es index size #2737
  README.md
  doc/es_stores.md
  doc/es_stores.pdf
  doc/migration.md
  doc/properties.org
  project.clj
  resources/ctia-default.properties
  src/ctia/entity/entities.clj
  src/ctia/entity/event.clj
  src/ctia/entity/event/crud.clj
  src/ctia/entity/event/store.clj
  src/ctia/entity/identity.clj
  src/ctia/properties.clj
  src/ctia/stores/es/crud.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/store.clj
  src/ctia/task/migration/migrate_es_stores.clj
  src/ctia/task/migration/store.clj
  src/ctia/task/rollover.clj
  test/ctia/bulk/routes_test.clj
  test/ctia/bundle/routes_test.clj
  test/ctia/flows/events_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/stores/identity_store_test.clj
  test/ctia/task/migration/migrate_es_stores_test.clj
  test/ctia/task/migration/store_test.clj
  test/ctia/task/rollover_test.clj
  test/ctia/test_helpers/es.clj
  test/ctia/test_helpers/fixtures.clj
Labels: review

#835 Fix typo in unlimited properties used for the rate limit
  src/ctia/auth/jwt.clj
  test/ctia/http/middleware/ratelimit_test.clj
Labels: review

#738 Removing usage of Elasticsearch field data cache
  src/ctia/entity/actor.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/data_table.clj
  src/ctia/entity/event.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/judgement/es_store.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship.clj
  src/ctia/entity/sighting/es_store.clj
  src/ctia/entity/tool.clj
  src/ctia/entity/vulnerability/mapping.clj
  src/ctia/entity/weakness/mapping.clj
  src/ctia/stores/es/crud.clj
  src/ctia/stores/es/mapping.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/mapping_test.clj
  test/ctia/test_helpers/access_control.clj
Labels: review
