Repository threatgrid/ctia, pull requests merged in 2020-10, with the labels that each got.

#1008 fix ductile protocol parameter
  doc/migration.md
  resources/ctia-default.properties
  src/ctia/properties.clj
  src/ctia/task/migration/store.clj
  test/ctia/properties_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/task/migration/store_test.clj
Labels: review

#1012 fix update description
  src/ctia/http/routes/crud.clj
Labels: review

#1010 issue-1009: Add support for configurations in Vulnerability entity
  project.clj
  src/ctia/entity/vulnerability/mapping.clj
  test/data/vulnerability.graphql
  test/data/vulnerability_fragments.graphql
Labels: review

#1015 Implement go/start/stop for repl dev
  README.md
  dev/user.clj
  project.clj
  src/ctia/init.clj
Labels: dev

#1011 Better isolate fake whoami service
  src/ctia/auth/threatgrid.clj
  src/ctia/init.clj
  test/ctia/auth/threatgrid_test.clj
  test/ctia/bulk/routes_test.clj
  test/ctia/bundle/routes_test.clj
  test/ctia/entity/actor_test.clj
  test/ctia/entity/asset_mapping_test.clj
  test/ctia/entity/asset_properties_test.clj
  test/ctia/entity/asset_test.clj
  test/ctia/entity/attack_pattern_test.clj
  test/ctia/entity/campaign_test.clj
  test/ctia/entity/casebook_test.clj
  test/ctia/entity/coa_test.clj
  test/ctia/entity/data_table_test.clj
  test/ctia/entity/event_test.clj
  test/ctia/entity/feed_test.clj
  test/ctia/entity/feedback_test.clj
  test/ctia/entity/identity_assertion_test.clj
  test/ctia/entity/incident_test.clj
  test/ctia/entity/indicator_test.clj
  test/ctia/entity/investigation_test.clj
  test/ctia/entity/judgement_test.clj
  test/ctia/entity/malware_test.clj
  test/ctia/entity/relationship_test.clj
  test/ctia/entity/sighting_test.clj
  test/ctia/entity/target_record_test.clj
  test/ctia/entity/tool_test.clj
  test/ctia/entity/vulnerability_test.clj
  test/ctia/entity/weakness_test.clj
  test/ctia/entity/web_test.clj
  test/ctia/http/middleware/cache_control_test.clj
  test/ctia/http/routes/graphql/attack_pattern_test.clj
  test/ctia/http/routes/graphql/incident_test.clj
  test/ctia/http/routes/graphql/investigation_test.clj
  test/ctia/http/routes/graphql/malware_test.clj
  test/ctia/http/routes/graphql/tool_test.clj
  test/ctia/http/routes/graphql/vulnerability_test.clj
  test/ctia/http/routes/graphql/weakness_test.clj
  test/ctia/http/routes/graphql_test.clj
  test/ctia/http/routes/observable/judgements_indicators_test.clj
  test/ctia/http/routes/observable/judgements_test.clj
  test/ctia/http/routes/observable/sightings_incidents_test.clj
  test/ctia/http/routes/observable/sightings_indicators_test.clj
  test/ctia/http/routes/observable/sightings_test.clj
  test/ctia/http/routes/observable/verdict_test.clj
  test/ctia/http/routes/status_test.clj
  test/ctia/http/routes/version_test.clj
  test/ctia/store_service_test.clj
  test/ctia/task/check_es_stores_test.clj
  test/ctia/task/migration/migrate_es_stores_test.clj
  test/ctia/task/migration/store_test.clj
  test/ctia/task/rollover_test.clj
  test/ctia/task/update_mapping_test.clj
  test/ctia/test_helpers/access_control.clj
  test/ctia/test_helpers/aggregate.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/fake_whoami_service.clj
Labels: review

#1019 Convert entity-routes macro to function
  src/ctia/http/handler.clj
  test/ctia/http/handler_test.clj
Labels: dev, review

#1020 Remove http routes for disabled entities
  src/ctia/features_service.clj
  src/ctia/http/handler.clj
  src/ctia/http/server_service.clj
  src/ctia/init.clj
  src/ctia/properties.clj
  src/ctia/schemas/core.clj
  test/ctia/features_service_test.clj
Labels: review

#1026 Use GitHub Actions for PR builds, add cron, parallelize Travis pushes
  .github/workflows/pr.yml
  .travis.yml
  build/run-tests.sh
  dev-resources/circleci_test/config.clj
  dev/ctia/dev/split_tests.clj
  project.clj
  scripts/shellcheck-build.sh
  test/ctia/lib/collection_test.clj
Labels: dev, review
