Repository threatgrid/ctia, pull requests merged in 2020-11, with the labels that each got.

#1007 Replace `get-free-port` with explicit port 0 config
  doc/properties.org
  src/ctia/bulk/core.clj
  src/ctia/bundle/core.clj
  src/ctia/bundle/schemas.clj
  src/ctia/domain/entities.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/feed.clj
  src/ctia/entity/feed/schemas.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/relationship.clj
  src/ctia/flows/crud.clj
  src/ctia/graphql/schemas.clj
  src/ctia/graphql_service.clj
  src/ctia/graphql_service_core.clj
  src/ctia/http/routes/crud.clj
  src/ctia/http/server.clj
  src/ctia/http/server_service.clj
  src/ctia/http/server_service_core.clj
  src/ctia/init.clj
  src/ctia/observable/graphql/schemas.clj
  src/ctia/observable/routes.clj
  src/ctia/properties.clj
  src/ctia/schemas/core.clj
  src/ctia/schemas/graphql/helpers.clj
  src/ctia/schemas/graphql/resolvers.clj
  src/ctia/task/codegen.clj
  test/ctia/bulk/routes_test.clj
  test/ctia/bundle/core_test.clj
  test/ctia/entity/event_test.clj
  test/ctia/entity/web_test.clj
  test/ctia/http/generative/properties.clj
  test/ctia/http/routes/observable/judgements_indicators_test.clj
  test/ctia/http/routes/observable/sightings_incidents_test.clj
  test/ctia/http/routes/observable/sightings_indicators_test.clj
  test/ctia/http/routes/pagination_test.clj
  test/ctia/schemas/graphql/helpers_test.clj
  test/ctia/schemas/utils_test.clj
  test/ctia/test_helpers/benchmark.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/crud.clj
  test/ctia/test_helpers/http.clj
Labels: review

#1023 Bump CTIM from 1.0.21->1.0.22
  project.clj
Labels: QAVerified, schema

#1013 Es7 init
  .travis.yml
  containers/dev/docker-compose.yml
  dev/ctia/dev/split_tests.clj
  project.clj
  resources/ctia-default.properties
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/feed.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/judgement/es_store.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/sighting/es_store.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/properties.clj
  src/ctia/stores/es/crud.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/mapping.clj
  src/ctia/stores/es/store.clj
  src/ctia/task/migration/store.clj
  src/ctia/task/update_mapping.clj
  test/ctia/bundle/core_test.clj
  test/ctia/encryption_test.clj
  test/ctia/entity/casebook_test.clj
  test/ctia/entity/entities_test.clj
  test/ctia/entity/event_test.clj
  test/ctia/entity/web_test.clj
  test/ctia/events_test.clj
  test/ctia/features_service_test.clj
  test/ctia/flows/hooks_test.clj
  test/ctia/http/handler/allow_all_test.clj
  test/ctia/http/handler/static_auth_anonymous_test.clj
  test/ctia/http/handler/static_auth_test.clj
  test/ctia/http/middleware/cache_control_test.clj
  test/ctia/http/routes/swagger_json_test.clj
  test/ctia/http/server_test.clj
  test/ctia/lib/redis_test.clj
  test/ctia/logger_test.clj
  test/ctia/properties_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/stores/es/mapping_test.clj
  test/ctia/task/migration/migrate_es_stores_test.clj
  test/ctia/task/migration/store_test.clj
  test/ctia/task/rollover_test.clj
  test/ctia/task/update_mapping_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/crud.clj
  test/ctia/test_helpers/es.clj
Labels: review

#1028 Auto-balance tests, add test reporters
  .github/workflows/pr.yml
  .travis.yml
  README.md
  dev-resources/circleci_test/config.clj
  dev-resources/example_ctia_test_timings.edn
  dev/ctia/dev/split_tests.clj
  dev/ctia/dev/test_reporter.clj
  project.clj
  scripts/shellcheck-build.sh
  scripts/summarize-tests.clj
Labels: review, waiting feedback

#1035 Email Ambrose and GE on cron failures
  .travis.yml
Labels: review

#1036 Fix bulk test regression
  test/ctia/bulk/core_test.clj
Labels: dev, review

#1031 Expose POST /:id/expire routes for Judgement, AssetMapping, AssetProperties
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/judgement.clj
  src/ctia/http/routes/crud.clj
  test/ctia/entity/asset_mapping_test.clj
  test/ctia/entity/asset_properties_test.clj
  test/ctia/entity/judgement_test.clj
  test/ctia/test_helpers/crud.clj
Labels: review

#1039 Es7 store
  .travis.yml
  containers/dev/docker-compose.yml
  dev/ctia/dev/split_tests.clj
  project.clj
  resources/ctia-default.properties
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/event/store.clj
  src/ctia/entity/feed.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/judgement/es_store.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/sighting/es_store.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/properties.clj
  src/ctia/store.clj
  src/ctia/store_service.clj
  src/ctia/store_service_core.clj
  src/ctia/stores/es/crud.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/mapping.clj
  src/ctia/stores/es/store.clj
  src/ctia/task/migration/store.clj
  src/ctia/task/update_mapping.clj
  test/ctia/bundle/core_test.clj
  test/ctia/encryption_test.clj
  test/ctia/entity/casebook_test.clj
  test/ctia/entity/entities_test.clj
  test/ctia/entity/event_test.clj
  test/ctia/entity/web_test.clj
  test/ctia/events_test.clj
  test/ctia/features_service_test.clj
  test/ctia/flows/hooks_test.clj
  test/ctia/http/handler/allow_all_test.clj
  test/ctia/http/handler/static_auth_anonymous_test.clj
  test/ctia/http/handler/static_auth_test.clj
  test/ctia/http/middleware/cache_control_test.clj
  test/ctia/http/routes/swagger_json_test.clj
  test/ctia/http/server_test.clj
  test/ctia/lib/redis_test.clj
  test/ctia/logger_test.clj
  test/ctia/properties_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/stores/es/mapping_test.clj
  test/ctia/task/migration/migrate_es_stores_test.clj
  test/ctia/task/migration/store_test.clj
  test/ctia/task/rollover_test.clj
  test/ctia/task/update_mapping_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/crud.clj
  test/ctia/test_helpers/es.clj
Labels: review

#1040 Email on master push failures
  .travis.yml
Labels: review

#1042 make ES indices unique during tests
  test/ctia/flows/events_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/core_test.clj
  test/ctia/test_helpers/es.clj
Labels: dev, review

#1044 fix unique test indices and add test
  .github/workflows/pr.yml
  project.clj
  src/ctia/stores/es/init.clj
  test/ctia/auth/jwt_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/task/migration/migrate_es_stores_test.clj
  test/ctia/task/migration/store_test.clj
  test/ctia/task/rollover_test.clj
  test/ctia/task/update_mapping_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/core_test.clj
  test/ctia/test_helpers/es.clj
Labels: review
