Repository threatgrid/ctia, pull requests merged in 2021-03, with the labels that each got.

#1081 Actually pin JVM heap in CI
  project.clj
Labels: review

#1084 Fix master: Revert "Actually pin JVM heap in CI"
  project.clj
Labels: dev, review

#1082 Fix flaky logger test
  src/ctia/logging_core.clj
  test/ctia/logger_test.clj
Labels: review

#1091 Bump timeout to try and narrow down failing test
  test/ctia/flows/hooks/redis_event_hook_test.clj
Labels: dev, review

#1094 Only test wait_for with incidents
  src/ctia/http/routes/common.clj
  src/ctia/schemas/search_agg.clj
  test/ctia/http/routes/common_test.clj
  test/ctia/test_helpers/crud.clj
Labels: dev, review

#1092 Replace most of Travis cron with scalable GitHub Actions job and record individual deftest timings
  .github/workflows/pr.yml
  .travis.yml
  dev/ctia/dev/test_reporter.clj
  project.clj
  scripts/actions/install-bb.sh
  scripts/actions/install-lein.sh
  scripts/actions/print-matrix.clj
  scripts/summarize-tests.clj
Labels: dev, review

#1095 Centralize pagination tests
  .github/workflows/pr.yml
  build/run-tests.sh
  project.clj
  scripts/summarize-tests.clj
  src/ctia/entity/actor.clj
  src/ctia/entity/asset.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/feed.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity_assertion.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/investigation.clj
  src/ctia/entity/judgement.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship.clj
  src/ctia/entity/sighting.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/entity/vulnerability.clj
  src/ctia/entity/weakness.clj
  src/ctia/schemas/core.clj
  src/ctia/schemas/sorting.clj
  test/ctia/entity/actor_test.clj
  test/ctia/entity/asset_mapping_test.clj
  test/ctia/entity/asset_properties_test.clj
  test/ctia/entity/asset_test.clj
  test/ctia/entity/attack_pattern_test.clj
  test/ctia/entity/campaign_test.clj
  test/ctia/entity/casebook_test.clj
  test/ctia/entity/coa_test.clj
  test/ctia/entity/feed_test.clj
  test/ctia/entity/identity_assertion_test.clj
  test/ctia/entity/incident_test.clj
  test/ctia/entity/investigation_test.clj
  test/ctia/entity/judgement_test.clj
  test/ctia/entity/malware_test.clj
  test/ctia/entity/relationship_test.clj
  test/ctia/entity/sighting_test.clj
  test/ctia/entity/target_record_test.clj
  test/ctia/entity/tool_test.clj
  test/ctia/entity/vulnerability_test.clj
  test/ctia/entity/weakness_test.clj
  test/ctia/http/middleware/ratelimit_test.clj
  test/ctia/http/routes/common_test.clj
  test/ctia/http/routes/pagination_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/field_selection.clj
  test/ctia/test_helpers/http.clj
  test/ctia/test_helpers/pagination.clj
Labels: dev, review

#1096 read relationships file only once, less batches for rollover-test
  test/ctia/task/migration/store_test.clj
Labels: review

#1097 Fix Actions timing cache, fall back to cron timing if needed
  .github/workflows/pr.yml
  .travis.yml
  build/run-tests.sh
  project.clj
  scripts/actions/setup-env.clj
Labels: dev, wip

#1100 Cache future Clojure jars in Actions builds
  .github/workflows/pr.yml
  .travis.yml
  project.clj
  scripts/actions/print-matrix.clj
  test/ctia/lib/redis_test.clj
Labels: dev

#1101 Fix sightings gen test and enable casebook gen test for small inputs
  project.clj
  test/ctia/http/generative/es_store_spec.clj
  test/ctia/http/generative/properties.clj
  test/ctia/test_helpers/core.clj
Labels: dev, review

#1083 JWT middleware should respect expected content type
  project.clj
  src/ctia/auth/jwt.clj
  src/ctia/http/handler.clj
  src/ctia/http/server.clj
  test/ctia/entity/web_test.clj
Labels: review

#1089 Bundle Import Entities with Asset Refs
  project.clj
  src/ctia/bulk/core.clj
  src/ctia/bundle/core.clj
  src/ctia/bundle/routes.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/flows/crud.clj
  src/ctia/schemas/core.clj
  src/ctia/task/migration/migrations/investigation_actions.clj
  test/ctia/bundle/core_asset_ref_entities_test.clj
  test/ctia/bundle/routes_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/fixtures.clj
Labels: review

#1104 Split Travis cron
  .travis.yml
Labels: dev

#1105 Disable generative tests in Travis cron
  .travis.yml
Labels: review
