Repository threatgrid/ctia, pull requests merged in 2021-05, with the labels that each got.

#1078 Asset scope capabilities #4677
  resources/ctia-default.properties
  src/ctia/auth/jwt.clj
  src/ctia/properties.clj
  test/ctia/auth/jwt_test.clj
Labels: review

#1120 Travis: python 2 + SNI
  .travis.yml
Labels: review

#1109 Improve full-text search
  src/ctia/entity/vulnerability.clj
  src/ctia/http/routes/common.clj
  src/ctia/http/routes/crud.clj
  src/ctia/lib/utils.clj
  src/ctia/schemas/graphql/resolvers.clj
  src/ctia/schemas/search_agg.clj
  src/ctia/stores/es/crud.clj
  test/ctia/http/generative/fulltext_search_test.clj
  test/ctia/http/generative/properties.clj
  test/ctia/http/routes/common_test.clj
  test/ctia/lib/utils_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/crud.clj
  test/ctia/test_helpers/search.clj
Labels: review

#1122 renames asset-intel scope -> asset
  resources/ctia-default.properties
  src/ctia/auth/jwt.clj
  test/ctia/auth/jwt_test.clj
Labels: review

#1121 Schema helpers for Trapperkeeper graphs
  README.md
  src/ctia/bundle/core.clj
  src/ctia/entity/actor.clj
  src/ctia/entity/asset.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/data_table.clj
  src/ctia/entity/feed/schemas.clj
  src/ctia/entity/feedback/schemas.clj
  src/ctia/entity/identity_assertion.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/investigation/schemas.clj
  src/ctia/entity/judgement/schemas.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship/schemas.clj
  src/ctia/entity/sighting/schemas.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool/schemas.clj
  src/ctia/entity/vulnerability.clj
  src/ctia/entity/weakness.clj
  src/ctia/lib/utils.clj
  src/ctia/schemas/core.clj
  src/ctia/schemas/utils.clj
  src/ctia/stores/es/schemas.clj
  src/ctia/task/migration/store.clj
  test/ctia/entity/entities_test.clj
  test/ctia/lib/utils_test.clj
  test/ctia/schemas/utils_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/http.clj
Labels: dev, wip

#1103 Use new test.chuck logging features
  .github/workflows/pr.yml
  project.clj
  test/ctia/http/generative/properties.clj
Labels: dev, review

#1125 Add test suite for bb scripts and ability to test cron in PR's
  .github/workflows/pr.yml
  .travis.yml
  README.md
  bb.edn
  scripts-test/actions/actions_helpers_test.clj
  scripts-test/actions/print_matrix_test.clj
  scripts-test/actions/setup_env_test.clj
  scripts-test/actions/test_helpers.clj
  scripts-test/test_runner.clj
  scripts/actions/actions_helpers.clj
  scripts/actions/install-bb.sh
  scripts/actions/print-matrix.clj
  scripts/actions/print_matrix.clj
  scripts/actions/setup-env.clj
  scripts/actions/setup_env.clj
Labels: dev, review
