Repository threatgrid/ctia, pull requests merged in 2021-12, with the labels that each got.

#1175 ctim 1.1.10
  project.clj
Labels: review

#1178 trojan scanner
  .do_not_edit-trojansourcedetector.json
  .github/workflows/pr.yml
  .gitignore
  bb.edn
  build/deploy-actions.sh
  scripts-test/test_runner.clj
  scripts/actions/install-trojansourcedetector.sh
  scripts/do_not_edit-uberjar_trojansourcedetector.json
  scripts/generate-trojan-config.clj
  scripts/trojan-scan.sh
  scripts/uberjar-trojan-scan.clj
Labels: review, dev

#1179 fixes flaky test
  test/ctia/http/generative/fulltext_search_test.clj
Labels: review

#1180 Injects FeaturesService in StoreService
  src/ctia/schemas/services.clj
  src/ctia/store_service.clj
  src/ctia/store_service_core.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/schemas.clj
  src/ctia/task/migration/store.clj
  test/ctia/http/generative/fulltext_search_test.clj
  test/ctia/test_helpers/core.clj
  test/ctia/test_helpers/es.clj
  test/ctia/test_helpers/migration.clj
Labels: review

#1181 Fix ES7 migration rollover and strengthen migration parameter checks
  src/ctia/task/migration/migrate_es_stores.clj
  src/ctia/task/migration/store.clj
  test/ctia/task/migration/store_test.clj
Labels: review

#1148 bulk patch routes
  src/ctia/bulk/core.clj
  src/ctia/bulk/routes.clj
  src/ctia/bulk/schemas.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/judgement/es_store.clj
  src/ctia/entity/sighting/es_store.clj
  src/ctia/flows/crud.clj
  src/ctia/schemas/core.clj
  src/ctia/store.clj
  src/ctia/stores/es/store.clj
  test/ctia/bulk/core_test.clj
  test/ctia/bulk/routes_test.clj
  test/ctia/bundle/core_test.clj
  test/ctia/entity/incident_test.clj
  test/ctia/entity/sighting_test.clj
  test/ctia/flows/crud_test.clj
Labels: review

#1183 Disable test for Bundle import race condition
  test/ctia/bundle/routes_test.clj
Labels: review

#1186 Bump cron Clojure version
  project.clj
Labels: dev

#1182 Move enforce-search-fields fn inward
  src/ctia/entity/actor.clj
  src/ctia/entity/asset.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/event.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity_assertion.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/investigation.clj
  src/ctia/entity/judgement.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship.clj
  src/ctia/entity/sighting.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/entity/vulnerability.clj
  src/ctia/entity/weakness.clj
  src/ctia/http/routes/common.clj
  src/ctia/http/routes/crud.clj
  src/ctia/schemas/core.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/query.clj
  src/ctia/stores/es/schemas.clj
  test/ctia/http/generative/fulltext_search_test.clj
  test/ctia/http/routes/common_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
Labels: review

#1176 searchable-fields QA instructions document
  doc/searchable-fields-qa.md
Labels: review

#1184 ES 5.6.11
  containers/dev/docker-compose.yml
Labels: review
