Repository threatgrid/ctia, pull requests merged in 2021-06, with the labels that each got.

#1128 Issue-4744: Include `query-params` in CPE search
  src/ctia/entity/vulnerability.clj
Labels: bug, ready, review

#1126 SearchableEntityParams
  src/ctia/entity/actor.clj
  src/ctia/entity/asset.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/data_table.clj
  src/ctia/entity/event.clj
  src/ctia/entity/feed.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity_assertion.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/investigation.clj
  src/ctia/entity/judgement.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship.clj
  src/ctia/entity/sighting.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/entity/vulnerability.clj
  src/ctia/entity/weakness.clj
  src/ctia/http/routes/common.clj
  src/ctia/http/routes/crud.clj
Labels: review

#1130 deprecate old test fixture
  test/ctia/test_helpers/es.clj
Labels: review

#1129 Issue-4744: Add regression test for CPE Search paging
  test/ctia/entity/vulnerability_test.clj
  test/data/indices/sample-cpe-250.json
Labels: ready, review
