Repository threatgrid/ctia, pull requests merged in 2022-02, with the labels that each got.

#1193 Bump cron to clojure 1.11.0-beta1
  project.clj
Labels: review, dev

#1167 adds rename-search-fields fn
  doc/searchable-fields-qa.md
  src/ctia/entity/actor.clj
  src/ctia/entity/asset.clj
  src/ctia/entity/asset_mapping.clj
  src/ctia/entity/asset_properties.clj
  src/ctia/entity/attack_pattern.clj
  src/ctia/entity/campaign.clj
  src/ctia/entity/casebook.clj
  src/ctia/entity/coa.clj
  src/ctia/entity/event.clj
  src/ctia/entity/feedback.clj
  src/ctia/entity/identity_assertion.clj
  src/ctia/entity/incident.clj
  src/ctia/entity/indicator.clj
  src/ctia/entity/investigation.clj
  src/ctia/entity/judgement.clj
  src/ctia/entity/malware.clj
  src/ctia/entity/relationship.clj
  src/ctia/entity/sighting.clj
  src/ctia/entity/target_record.clj
  src/ctia/entity/tool.clj
  src/ctia/entity/vulnerability.clj
  src/ctia/entity/weakness.clj
  src/ctia/http/routes/common.clj
  src/ctia/http/routes/crud.clj
  src/ctia/schemas/core.clj
  src/ctia/stores/es/crud.clj
  src/ctia/stores/es/init.clj
  src/ctia/stores/es/mapping.clj
  src/ctia/stores/es/query.clj
  src/ctia/stores/es/schemas.clj
  test/ctia/http/generative/fulltext_search_test.clj
  test/ctia/http/routes/common_test.clj
  test/ctia/stores/es/crud_test.clj
  test/ctia/stores/es/init_test.clj
  test/ctia/stores/es/query_test.clj
Labels: review, don't merge

#1192 Reduce noise in logs when running tests
  project.clj
  test-resources/.keepme
  test-resources/hooks/AutoloadHook.jar
  test-resources/hooks/JarHook.jar
  test-resources/hooks/hook-example-0.1.0-SNAPSHOT.jar
  test-resources/logback-test.xml
Labels: review

#1187 bulk update
  src/ctia/bulk/core.clj
  src/ctia/bulk/routes.clj
  src/ctia/bulk/schemas.clj
  src/ctia/flows/crud.clj
  src/ctia/stores/es/crud.clj
  test/ctia/bulk/core_test.clj
  test/ctia/bulk/routes_test.clj
  test/ctia/flows/crud_test.clj
  test/ctia/test_helpers/crud.clj
Labels: review

#1197 fixed migration services
  src/ctia/task/migration/migrate_es_stores.clj
Labels: review

#1198 More detailed test feedback
  test/ctia/http/generative/fulltext_search_test.clj
Labels: dev
